version: "3.9"
services:
  postgres-db:
    image: postgres
    restart: always
    container_name: postgres-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/postgres
  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      - ./redis_volume_data:/data
    ports:
      - "6379:6379"

  redis_insight:
    image: redislabs/redisinsight
    container_name: redis_insight
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - ./redis_insight_volume_data:/db
    depends_on:
      - redis
